module Lulz
	class Country

   COUNTRIES = [ 'Andorra',
               'United Arab Emirates',
               'Afghanistan',
               'Antigua and Barbuda',
               'Anguilla',
               'Albania',
               'Armenia',
               'Netherlands Antilles',
               'Angola',
               'Antarctica',
               'Argentina',
'American Samoa',
'Austria',
'Australia',
'Aruba',
'Aland Islands',
'Azerbaijan',
'Bosnia',
'Barbados',
'Bangladesh',
'Belgium',
'Burkina Faso',
'Bulgaria',
'Bahrain',
'Burundi',
'Benin',
'Saint Barthelemy',
'Bermuda',
'Brunei Darussalam',
'Bolivia',
'Brazil',
'Bahamas',
'Bhutan',
'Bouvet Island',
'Botswana',
'Belarus',
'Belize',
'Canada',
'Cocos (Keeling) Islands',
'Congo, the Democratic Republic of the',
'Central African Republic',
'Congo',
'Switzerland',
'Cote d\'Ivoire',
'Cook Islands',
'Chile',
'Cameroon',
'China',
'Colombia',
'Costa Rica',
'Cuba',
'Cape Verde',
'Christmas Island',
'Cyprus',
'Czech Republic',
'Germany',
'Djibouti',
'Denmark',
'Dominica',
'Dominican Republic',
'Algeria',
'Ecuador',
'Estonia',
'Egypt',
'Western Sahara',
'Eritrea',
'Spain',
'Ethiopia',
'Finland',
'Fiji',
'Falkland Islands',
'Micronesia',
'Faroe Islands',
'France',
'Gabon',
'United Kingdom',
'United Kingdom',
'Grenada',
'Georgia',
'French Guiana',
'Guernsey',
'Ghana',
'Gibraltar',
'Greenland',
'Gambia',
'Guinea',
'Guadeloupe',
'Equatorial Guinea',
'Greece',
'South Georgia',
'Guatemala',
'Guam',
'Guinea-Bissau',
'Guyana',
'Hong Kong',
'Heard Island and McDonald Islands',
'Honduras',
'Croatia',
'Haiti',
'Hungary',
'Indonesia',
'Ireland',
'Israel',
'Isle of Man',
'India',
'British Indian Ocean Territory',
'Iraq',
'Iran',
'Iceland',
'Italy',
'Jersey',
'Jamaica',
'Jordan',
'Japan',
'Kenya',
'Kyrgyzstan',
'Cambodia',
'Kiribati',
'Comoros',
'Saint Kitts',
'North Korea',
'Korea',
'Kuwait',
'Cayman Islands',
'Kazakhstan',
'Lao',
'Lebanon',
'Saint Lucia',
'Liechtenstein',
'Sri Lanka',
'Liberia',
'Lesotho',
'Lithuania',
'Luxembourg',
'Latvia',
'Libya',
'Morocco',
'Monaco',
'Moldova',
'Montenegro',
'Saint Martin',
'Madagascar',
'Marshall Islands',
'Macedonia',
'Mali',
'Myanmar',
'Mongolia',
'Macao',
'Northern Mariana Islands',
'Martinique',
'Mauritania',
'Montserrat',
'Malta',
'Mauritius',
'Maldives',
'Malawi',
'Mexico',
'Malaysia',
'Mozambique',
'Namibia',
'New Caledonia',
'Niger',
'Norfolk Island',
'Nigeria',
'Nicaragua',
'Netherlands',
'Norway',
'Nepal',
'Nauru',
'Niue',
'New Zealand',
'Oman',
'Panama',
'Peru',
'French Polynesia',
'Papua New Guinea',
'Philippines',
'Pakistan',
'Poland',
'Saint Pierre and Miquelon',
'Pitcairn',
'Puerto Rico',
'Palestinian Territory, Occupied',
'Portugal',
'Palau',
'Paraguay',
'Qatar',
'Reunion',
'Romania',
'Serbia',
'Russian Federation',
'Rwanda',
'Saudi Arabia',
'Solomon Islands',
'Seychelles',
'Sudan',
'Sweden',
'Singapore',
'Saint Helena',
'Slovenia',
'Svalbard and Jan Mayen',
'Slovakia',
'Sierra Leone',
'San Marino',
'Senegal',
'Somalia',
'Suriname',
'Sao Tome and Principe',
'El Salvador',
'Syrian Arab Republic',
'Swaziland',
'Turks and Caicos Islands',
'Chad',
'French Southern Territories',
'Togo',
'Thailand',
'Tajikistan',
'Tokelau',
'Timor-Leste',
'Turkmenistan',
'Tunisia',
'Tonga',
'Turkey',
'Trinidad',
'Tuvalu',
'Taiwan',
'Tanzania',
'Ukraine',
'Uganda',
'United States',
'Uruguay',
'Uzbekistan',
'Holy See',
'Saint Vincent',
'Venezuela',
'Virgin Islands, British',
'Virgin Islands',
'Viet Nam',
'Vanuatu',
'Wallis and Futuna',
'Samoa',
'Yemen',
'Mayotte',
'South Africa',
'Zambia',
'Zimbabwe']

   C3={'ABW' => 'Aruba',
'AFG' => 'Afghanistan',
'AGO' => 'Angola',
'AIA' => 'Anguilla',
'ALA' => 'land Islands',
'ALB' => 'Albania',
'AND' => 'Andorra',
'ANT' => 'Netherlands Antilles',
'ARE' => 'United Arab Emirates',
'ARG' => 'Argentina',
'ARM' => 'Armenia',
'ASM' => 'American Samoa',
'ATA' => 'Antarctica',
'ATF' => 'French Southern Territories',
'ATG' => 'Antigua and Barbuda',
'AUS' => 'Australia',
'AUT' => 'Austria',
'AZE' => 'Azerbaijan',
'BDI' => 'Burundi',
'BEL' => 'Belgium',
'BEN' => 'Benin',
'BFA' => 'Burkina Faso',
'BGD' => 'Bangladesh',
'BGR' => 'Bulgaria',
'BHR' => 'Bahrain',
'BHS' => 'Bahamas',
'BIH' => 'Bosnia and Herzegovina',
'BLM' => 'Saint Barthelemy',
'BLR' => 'Belarus',
'BLZ' => 'Belize',
'BMU' => 'Bermuda',
'BOL' => 'Bolivia',
'BRA' => 'Brazil',
'BRB' => 'Barbados',
'BRN' => 'Brunei Darussalam',
'BTN' => 'Bhutan',
'BVT' => 'Bouvet Island',
'BWA' => 'Botswana',
'CAF' => 'Central African Republic',
'CAN' => 'Canada',
'CCK' => 'Cocos (Keeling) Islands',
'CHE' => 'Switzerland',
'CHL' => 'Chile',
'CHN' => 'China',
'CIV' => 'Cote d\'Ivoire',
'CMR' => 'Cameroon',
'COD' => 'Congo, the Democratic Republic of the',
'COG' => 'Congo',
'COK' => 'Cook Islands',
'COL' => 'Colombia',
'COM' => 'Comoros',
'CPV' => 'Cape Verde',
'CRI' => 'Costa Rica',
'CUB' => 'Cuba',
'CXR' => 'Christmas Island',
'CYM' => 'Cayman Islands',
'CYP' => 'Cyprus',
'CZE' => 'Czech Republic',
'DEU' => 'Germany',
'DJI' => 'Djibouti',
'DMA' => 'Dominica',
'DNK' => 'Denmark',
'DOM' => 'Dominican Republic',
'DZA' => 'Algeria',
'ECU' => 'Ecuador',
'EGY' => 'Egypt',
'ERI' => 'Eritrea',
'ESH' => 'Western Sahara',
'ESP' => 'Spain',
'EST' => 'Estonia',
'ETH' => 'Ethiopia',
'FIN' => 'Finland',
'FJI' => 'Fiji',
'FLK' => 'Falkland Islands (Malvinas)',
'FRA' => 'France',
'FRO' => 'Faroe Islands',
'FSM' => 'Micronesia',
'GAB' => 'Gabon',
'GBR' => 'United Kingdom',
'GEO' => 'Georgia',
'GGY' => 'Guernsey',
'GHA' => 'Ghana',
'GIB' => 'Gibraltar',
'GIN' => 'Guinea',
'GLP' => 'Guadeloupe',
'GMB' => 'Gambia',
'GNB' => 'Guinea-Bissau',
'GNQ' => 'Equatorial Guinea',
'GRC' => 'Greece',
'GRD' => 'Grenada',
'GRL' => 'Greenland',
'GTM' => 'Guatemala',
'GUF' => 'French Guiana',
'GUM' => 'Guam',
'GUY' => 'Guyana',
'HKG' => 'Hong Kong',
'HMD' => 'Heard Island and McDonald Islands',
'HND' => 'Honduras',
'HRV' => 'Croatia',
'HTI' => 'Haiti',
'HUN' => 'Hungary',
'IDN' => 'Indonesia',
'IMN' => 'Isle of Man',
'IND' => 'India',
'IOT' => 'British Indian Ocean Territory',
'IRL' => 'Ireland',
'IRN' => 'Iran',
'IRQ' => 'Iraq',
'ISL' => 'Iceland',
'ISR' => 'Israel',
'ITA' => 'Italy',
'JAM' => 'Jamaica',
'JEY' => 'Jersey',
'JOR' => 'Jordan',
'JPN' => 'Japan',
'KAZ' => 'Kazakhstan',
'KEN' => 'Kenya',
'KGZ' => 'Kyrgyzstan',
'KHM' => 'Cambodia',
'KIR' => 'Kiribati',
'KNA' => 'Saint Kitts and Nevis',
'KOR' => 'Korea, Republic of',
'KWT' => 'Kuwait',
'LAO' => 'Lao',
'LBN' => 'Lebanon',
'LBR' => 'Liberia',
'LBY' => 'Libyan Arab Jamahiriya',
'LCA' => 'Saint Lucia',
'LIE' => 'Liechtenstein',
'LKA' => 'Sri Lanka',
'LSO' => 'Lesotho',
'LTU' => 'Lithuania',
'LUX' => 'Luxembourg',
'LVA' => 'Latvia',
'MAC' => 'Macao',
'MAF' => 'Saint Martin (French part)',
'MAR' => 'Morocco',
'MCO' => 'Monaco',
'MDA' => 'Moldova, Republic of',
'MDG' => 'Madagascar',
'MDV' => 'Maldives',
'MEX' => 'Mexico',
'MHL' => 'Marshall Islands',
'MKD' => 'Macedonia, the former Yugoslav Republic of',
'MLI' => 'Mali',
'MLT' => 'Malta',
'MMR' => 'Myanmar',
'MNE' => 'Montenegro',
'MNG' => 'Mongolia',
'MNP' => 'Northern Mariana Islands',
'MOZ' => 'Mozambique',
'MRT' => 'Mauritania',
'MSR' => 'Montserrat',
'MTQ' => 'Martinique',
'MUS' => 'Mauritius',
'MWI' => 'Malawi',
'MYS' => 'Malaysia',
'MYT' => 'Mayotte',
'NAM' => 'Namibia',
'NCL' => 'New Caledonia',
'NER' => 'Niger',
'NFK' => 'Norfolk Island',
'NGA' => 'Nigeria',
'NIC' => 'Nicaragua',
'NIU' => 'Niue',
'NLD' => 'Netherlands',
'NOR' => 'Norway',
'NPL' => 'Nepal',
'NRU' => 'Nauru',
'NZL' => 'New Zealand',
'OMN' => 'Oman',
'PAK' => 'Pakistan',
'PAN' => 'Panama',
'PCN' => 'Pitcairn',
'PER' => 'Peru',
'PHL' => 'Philippines',
'PLW' => 'Palau',
'PNG' => 'Papua New Guinea',
'POL' => 'Poland',
'PRI' => 'Puerto Rico',
'PRK' => 'Korea',
'PRT' => 'Portugal',
'PRY' => 'Paraguay',
'PSE' => 'Palestinian Territory, Occupied',
'PYF' => 'French Polynesia',
'QAT' => 'Qatar',
'REU' => 'Reunion',
'ROU' => 'Romania',
'RUS' => 'Russian Federation',
'RWA' => 'Rwanda',
'SAU' => 'Saudi Arabia',
'SDN' => 'Sudan',
'SEN' => 'Senegal',
'SGP' => 'Singapore',
'SGS' => 'South Georgia and the South Sandwich Islands',
'SHN' => 'Saint Helena',
'SJM' => 'Svalbard and Jan Mayen',
'SLB' => 'Solomon Islands',
'SLE' => 'Sierra Leone',
'SLV' => 'El Salvador',
'SMR' => 'San Marino',
'SOM' => 'Somalia',
'SPM' => 'Saint Pierre and Miquelon',
'SRB' => 'Serbia',
'STP' => 'Sao Tome and Principe',
'SUR' => 'Suriname',
'SVK' => 'Slovakia',
'SVN' => 'Slovenia',
'SWE' => 'Sweden',
'SWZ' => 'Swaziland',
'SYC' => 'Seychelles',
'SYR' => 'Syrian Arab Republic',
'TCA' => 'Turks and Caicos Islands',
'TCD' => 'Chad',
'TGO' => 'Togo',
'THA' => 'Thailand',
'TJK' => 'Tajikistan',
'TKL' => 'Tokelau',
'TKM' => 'Turkmenistan',
'TLS' => 'Timor-Leste',
'TON' => 'Tonga',
'TTO' => 'Trinidad and Tobago',
'TUN' => 'Tunisia',
'TUR' => 'Turkey',
'TUV' => 'Tuvalu',
'TWN' => 'Taiwan, Province of China',
'TZA' => 'Tanzania, United Republic of',
'UGA' => 'Uganda',
'UKR' => 'Ukraine',
'UMI' => 'United States Minor Outlying Islands',
'URY' => 'Uruguay',
'USA' => 'United States',
'UZB' => 'Uzbekistan',
'VAT' => 'Holy See (Vatican City State)',
'VCT' => 'Saint Vincent and the Grenadines',
'VEN' => 'Venezuela, Bolivarian Republic of',
'VGB' => 'Virgin Islands, British',
'VIR' => 'Virgin Islands, U.S.',
'VNM' => 'Viet Nam',
'VUT' => 'Vanuatu',
'WLF' => 'Wallis and Futuna',
'WSM' => 'Samoa',
'YEM' => 'Yemen',
'ZAF' => 'South Africa',
'ZMB' => 'Zambia',
'ZWE' => 'Zimbabwe'}

C2 = {'AD' => 'Andorra',
'AE' => 'United Arab Emirates',
'AF' => 'Afghanistan',
'AG' => 'Antigua and Barbuda',
'AI' => 'Anguilla',
'AL' => 'Albania',
'AM' => 'Armenia',
'AN' => 'Netherlands Antilles',
'AO' => 'Angola',
'AQ' => 'Antarctica',
'AR' => 'Argentina',
'AS' => 'American Samoa',
'AT' => 'Austria',
'AU' => 'Australia',
'AW' => 'Aruba',
'AX' => 'Aland Islands',
'AZ' => 'Azerbaijan',
'BA' => 'Bosnia and Herzegovina',
'BB' => 'Barbados',
'BD' => 'Bangladesh',
'BE' => 'Belgium',
'BF' => 'Burkina Faso',
'BG' => 'Bulgaria',
'BH' => 'Bahrain',
'BI' => 'Burundi',
'BJ' => 'Benin',
'BL' => 'Saint Barthelemy',
'BM' => 'Bermuda',
'BN' => 'Brunei Darussalam',
'BO' => 'Bolivia',
'BR' => 'Brazil',
'BS' => 'Bahamas',
'BT' => 'Bhutan',
'BV' => 'Bouvet Island',
'BW' => 'Botswana',
'BY' => 'Belarus',
'BZ' => 'Belize',
'CA' => 'Canada',
'CC' => 'Cocos (Keeling) Islands',
'CD' => 'Congo, the Democratic Republic of the',
'CF' => 'Central African Republic',
'CG' => 'Congo',
'CH' => 'Switzerland',
'CI' => 'Cote d\'Ivoire',
'CK' => 'Cook Islands',
'CL' => 'Chile',
'CM' => 'Cameroon',
'CN' => 'China',
'CO' => 'Colombia',
'CR' => 'Costa Rica',
'CU' => 'Cuba',
'CV' => 'Cape Verde',
'CX' => 'Christmas Island',
'CY' => 'Cyprus',
'CZ' => 'Czech Republic',
'DE' => 'Germany',
'DJ' => 'Djibouti',
'DK' => 'Denmark',
'DM' => 'Dominica',
'DO' => 'Dominican Republic',
'DZ' => 'Algeria',
'EC' => 'Ecuador',
'EE' => 'Estonia',
'EG' => 'Egypt',
'EH' => 'Western Sahara',
'ER' => 'Eritrea',
'ES' => 'Spain',
'ET' => 'Ethiopia',
'FI' => 'Finland',
'FJ' => 'Fiji',
'FK' => 'Falkland Islands',
'FM' => 'Micronesia',
'FO' => 'Faroe Islands',
'FR' => 'France',
'GA' => 'Gabon',
'GB' => 'United Kingdom',
'UK' => 'United Kingdom',
'GD' => 'Grenada',
'GE' => 'Georgia',
'GF' => 'French Guiana',
'GG' => 'Guernsey',
'GH' => 'Ghana',
'GI' => 'Gibraltar',
'GL' => 'Greenland',
'GM' => 'Gambia',
'GN' => 'Guinea',
'GP' => 'Guadeloupe',
'GQ' => 'Equatorial Guinea',
'GR' => 'Greece',
'GS' => 'South Georgia',
'GT' => 'Guatemala',
'GU' => 'Guam',
'GW' => 'Guinea-Bissau',
'GY' => 'Guyana',
'HK' => 'Hong Kong',
'HM' => 'Heard Island and McDonald Islands',
'HN' => 'Honduras',
'HR' => 'Croatia',
'HT' => 'Haiti',
'HU' => 'Hungary',
'ID' => 'Indonesia',
'IE' => 'Ireland',
'IL' => 'Israel',
'IM' => 'Isle of Man',
'IN' => 'India',
'IO' => 'British Indian Ocean Territory',
'IQ' => 'Iraq',
'IR' => 'Iran',
'IS' => 'Iceland',
'IT' => 'Italy',
'JE' => 'Jersey',
'JM' => 'Jamaica',
'JO' => 'Jordan',
'JP' => 'Japan',
'KE' => 'Kenya',
'KG' => 'Kyrgyzstan',
'KH' => 'Cambodia',
'KI' => 'Kiribati',
'KM' => 'Comoros',
'KN' => 'Saint Kitts',
'KP' => 'North Korea',
'KR' => 'Korea',
'KW' => 'Kuwait',
'KY' => 'Cayman Islands',
'KZ' => 'Kazakhstan',
'LA' => 'Lao',
'LB' => 'Lebanon',
'LC' => 'Saint Lucia',
'LI' => 'Liechtenstein',
'LK' => 'Sri Lanka',
'LR' => 'Liberia',
'LS' => 'Lesotho',
'LT' => 'Lithuania',
'LU' => 'Luxembourg',
'LV' => 'Latvia',
'LY' => 'Libya',
'MA' => 'Morocco',
'MC' => 'Monaco',
'MD' => 'Moldova',
'ME' => 'Montenegro',
'MF' => 'Saint Martin',
'MG' => 'Madagascar',
'MH' => 'Marshall Islands',
'MK' => 'Macedonia',
'ML' => 'Mali',
'MM' => 'Myanmar',
'MN' => 'Mongolia',
'MO' => 'Macao',
'MP' => 'Northern Mariana Islands',
'MQ' => 'Martinique',
'MR' => 'Mauritania',
'MS' => 'Montserrat',
'MT' => 'Malta',
'MU' => 'Mauritius',
'MV' => 'Maldives',
'MW' => 'Malawi',
'MX' => 'Mexico',
'MY' => 'Malaysia',
'MZ' => 'Mozambique',
'NA' => 'Namibia',
'NC' => 'New Caledonia',
'NE' => 'Niger',
'NF' => 'Norfolk Island',
'NG' => 'Nigeria',
'NI' => 'Nicaragua',
'NL' => 'Netherlands',
'NO' => 'Norway',
'NP' => 'Nepal',
'NR' => 'Nauru',
'NU' => 'Niue',
'NZ' => 'New Zealand',
'OM' => 'Oman',
'PA' => 'Panama',
'PE' => 'Peru',
'PF' => 'French Polynesia',
'PG' => 'Papua New Guinea',
'PH' => 'Philippines',
'PK' => 'Pakistan',
'PL' => 'Poland',
'PM' => 'Saint Pierre and Miquelon',
'PN' => 'Pitcairn',
'PR' => 'Puerto Rico',
'PS' => 'Palestinian Territory, Occupied',
'PT' => 'Portugal',
'PW' => 'Palau',
'PY' => 'Paraguay',
'QA' => 'Qatar',
'RE' => 'Reunion',
'RO' => 'Romania',
'RS' => 'Serbia',
'RU' => 'Russian Federation',
'RW' => 'Rwanda',
'SA' => 'Saudi Arabia',
'SB' => 'Solomon Islands',
'SC' => 'Seychelles',
'SD' => 'Sudan',
'SE' => 'Sweden',
'SG' => 'Singapore',
'SH' => 'Saint Helena',
'SI' => 'Slovenia',
'SJ' => 'Svalbard and Jan Mayen',
'SK' => 'Slovakia',
'SL' => 'Sierra Leone',
'SM' => 'San Marino',
'SN' => 'Senegal',
'SO' => 'Somalia',
'SR' => 'Suriname',
'ST' => 'Sao Tome and Principe',
'SV' => 'El Salvador',
'SY' => 'Syrian Arab Republic',
'SZ' => 'Swaziland',
'TC' => 'Turks and Caicos Islands',
'TD' => 'Chad',
'TF' => 'French Southern Territories',
'TG' => 'Togo',
'TH' => 'Thailand',
'TJ' => 'Tajikistan',
'TK' => 'Tokelau',
'TL' => 'Timor-Leste',
'TM' => 'Turkmenistan',
'TN' => 'Tunisia',
'TO' => 'Tonga',
'TR' => 'Turkey',
'TT' => 'Trinidad',
'TV' => 'Tuvalu',
'TW' => 'Taiwan',
'TZ' => 'Tanzania',
'UA' => 'Ukraine',
'UG' => 'Uganda',
'US' => 'United States',
'UY' => 'Uruguay',
'UZ' => 'Uzbekistan',
'VA' => 'Holy See',
'VC' => 'Saint Vincent',
'VE' => 'Venezuela',
'VG' => 'Virgin Islands, British',
'VI' => 'Virgin Islands',
'VN' => 'Viet Nam',
'VU' => 'Vanuatu',
'WF' => 'Wallis and Futuna',
'WS' => 'Samoa',
'YE' => 'Yemen',
'YT' => 'Mayotte',
'ZA' => 'South Africa',
'ZM' => 'Zambia',
'ZW' => 'Zimbabwe'}

C4={
'England' => 'United Kingdom',
'Britain' => 'United Kingdom'
}


     equality_on :country
	
      def initialize(c=nil)
         self.country=normalize(c)
      
      end

      def to_cc
      	cc=C2.invert[country].downcase
			cc="uk" if cc=="gb"
			return cc
      end

      def normalize(c)
         c2=c.to_s.strip.downcase
         return nil if c2.blank?
         COUNTRIES.each do |country|
            return country if c2==country.downcase
         end
 
         COUNTRIES.each do |country|
            return country if c2.include?(country.downcase)
         end

         C3.each do |code, country|
            return country if c2==code.downcase
         end

         C2.each do |code, country|
            return country if c2==code.downcase
         end

	 C4.each do |alt, country|
            return country if c2==alt.downcase
         end


         return nil


      end



	end
end
